### ISSUE TITLE
Feature: Support for `isAdmin` flag in the ping/profile endpoints

### ISSUE THREAD

**Issue by atharva3010** [pcl-labs/meredith-core#331]
It will be great if we can return a flag `isAdmin` in the response of ping endpoint as it's used in the before router hook of BrowTricks and can be used to show/hide the link to the admin page, and also redirect non-admins back to their home page in case they do end up on the admin page.

**Comment by StrangeWill** [comment]
Added `isAdmin` to profile call in d47c02675f4f14c366fd255ab2170eefed23d766

**Comment by StrangeWill** [comment]
Let me know if you want it in _both_, but both seemed overkill.
