### ISSUE TITLE
Feature: Sorting for ​/api​/v0​/users

### ISSUE THREAD

**Issue by atharva3010** [pcl-labs/meredith-core#333]
Quoting @StrangeWill for context

> Yeah, I was asking how we want to sort it
> I guess that's first name
> Done, first then last.

Need the responses to be returned sorted from the backend, by first name then last name

**Comment by StrangeWill** [comment]
81f7866d31c5014e48d50c13f84af94581e89b3d

Is it not already?

**Comment by StrangeWill** [comment]
Nope, queryable type mismatch, fixed.

**Comment by StrangeWill** [comment]
Fixed in 43344de3179cf5afcb1e0b9fbeacf5e276b80288
