### ISSUE TITLE
[BUG]: Query not working on `/api/v0/users`, returns 500 error

### ISSUE THREAD

**Issue by atharva3010** [pcl-labs/meredith-core#335]
`GET | https://stagingapi.whynot.earth/api/v0/users?Query=A&Page=0`

Response:
Status: 500
Internal Server Error
```
{"message":"Something went wrong, if problem persisted please contact chris@whynot.earth"}
```

**Comment by StrangeWill** [comment]
Fixed how we do string concatenation so you can do things like search for "firstname lastname".

Technically blows away the index so maybe we want to remove that 🤔

**Comment by StrangeWill** [comment]
Fixed
