### ISSUE TITLE
Password Reset Flow Requires E-Mail/UserName To Be Fed Back In During Reset

### ISSUE THREAD

**Issue by atharva3010** [pcl-labs/meredith-core#338]
```
Request URL: https://stagingapi.whynot.earth/api/v0/authentication/forgotpasswordreset
Request Method: POST
Status Code: 400 
```
Payload:
```
{"token":"xxxxxxxxxxxxxxxxxxxxxxxxxx","password":"test","confirmPassword":"test"}
```
Response:
```
{"errors":{"Email":["Provide email or username"],"UserName":["Provide email or username"]},"type":"https://tools.ietf.org/html/rfc7231#section-6.5.1","title":"One or more validation errors occurred.","status":400,"traceId":"00-dd712c02d9239648bd95a8146c00ad59-da81ab231a5a024e-00"}
```

**Comment by StrangeWill** [comment]
Hmm, that is by design via the API, but I can do some stuff to make this a bit less clunky (eg: having to provide an e-mail during password reset).

I may technically swap this to an _enhancement_ since the API is designed to be annoying, but minor detail.

**Comment by StrangeWill** [comment]
BTW: our workaround on this on other platforms is for us to provide the ability to get the user ID via URL params and pass it back into the API with the password to be reset, supporting this _and the other methods_ is a bit clunky, but I'd rather the front-end up be annoying.

**Comment by StrangeWill** [comment]
We will return a user ID in the reset path, you should be able to return that back as the "userid" value and we'll use that for lookup.
